package com.jfa.cli;

public final class HelpText {
    private HelpText() {
    }

    public static String mainHelp() {
        return ""
                + "======== JFA — 内网 JVM 故障诊断助手 ========\n"
                + "主路径：诊断已有服务，无需 jfa start。\n"
                + "本产品执行短时堆代采样、应用日志倒查、以及双 hprof 对比；不要把“请自行查日志/对比 dump”当主路径。\n\n"
                + "安装包五个命令（bin/）:\n"
                + "  jfa                      # 列出可分析的 Java 进程（原 jfa discover）\n"
                + "  jfa --help  /  jfa help  # 推荐 JVM 配置（原 jfa help config / config recommend）\n"
                + "  jfa-analyze              # 活体诊断（原 jfa diagnose）\n"
                + "  jfa-file-analyze         # 离线分析（原 jfa analyze）\n"
                + "  jfa-collect              # 采集（原 jfa collect）\n"
                + "  jfa-config               # 与 jfa help 相同：推荐 JVM 配置\n\n"
                + "无参数时：jfa-analyze / jfa-file-analyze / jfa-collect 打印各自参数说明。\n\n"
                + "java -jar 兼容子命令（测试与脚本仍可用）:\n"
                + "  discover | diagnose | analyze | collect | help | config recommend\n"
                + "  register | evidence | status | show\n\n"
                + "用法:\n"
                + "  jfa-analyze --pid <pid> [--type auto|memory|thread] [--confirm]\n"
                + "  jfa-file-analyze --hprof file [--hprof-prev file] [--type memory]\n"
                + "  jfa-collect heapdump --pid n [--confirm]\n\n"
                + "主入口示例:\n"
                + "  jfa-analyze --pid <pid>                 # 默认全量 = memory + thread；无异常则为健康体检\n"
                + "  jfa-analyze --service <name>\n"
                + "  jfa-analyze --pid <pid> --type auto     # 与默认等价\n"
                + "  jfa-analyze --pid <pid> --type memory   # 只分析内存（含 jstat 采样 + 日志倒查）\n"
                + "  jfa-analyze --pid <pid> --type thread   # 只分析线程（含死锁）\n"
                + "  jfa-analyze --pid <pid> --type memory --compare-after 15m [--confirm]\n"
                + "      # 活体 A/B：dump1（复用已有 hprof 或采集）→ 采样+日志倒查 → 等待 → dump2 → 本产品对比\n"
                + "      # 一次 --confirm 覆盖本命令两次 dump\n\n"
                + "常用:\n"
                + "  jfa [--user u] [--main keyword] [--format json]\n"
                + "  jfa-file-analyze --evidence-dir d --type memory|thread|auto\n"
                + "  jfa-file-analyze --hprof file --gc-log file --type memory\n"
                + "  jfa-file-analyze --hprof newer.hprof --hprof-prev older.hprof --type memory\n"
                + "  jfa-collect threaddump --pid n\n"
                + "  jfa-collect heapdump --pid n [--confirm]\n"
                + "  jfa-collect sample --pid n --interval 5s --duration 60s [--confirm]\n"
                + "  jfa-config\n\n"
                + "诊断行为:\n"
                + "  默认向 stderr 打印 [JFA] 分步进度（解析目标、准备运行目录、日志倒查、jstat 采样、hprof 复用/采集、线程分析、compare 等待、写报告）。\n"
                + "  控制台不打印报告正文；结束后只打印报告绝对路径（报告文件 / JSON 报告）。\n"
                + "  --quiet 只关闭这些中途步骤；结束后仍打印报告绝对路径。\n"
                + "  --verbose 与默认进度兼容，可附加更细的路径/体积信息；主步骤不需要 --verbose。\n"
                + "  --format json 时 stdout 仍是纯 JSON，进度与路径在 stderr。\n"
                + "  每轮只写 <install>/reportfile/pid_<pid>/<yyyyMMdd-HHmmss>/（自包含：复用的 hprof/GC/日志会 copy 或硬链接进来）。\n"
                + "  cover.file=true 时先清空该 pid 目录；false 保留旧时间戳目录。\n"
                + "  活体 memory/auto：jstat -gcutil 短采样（sample.interval.seconds × sample.count，默认 5s×8）。\n"
                + "  日志倒查：默认分析时刻往前 10 分钟（log.lookback.minutes）；来源 --app-log / 已登记服务 / JVM 命令行。\n"
                + "  解析不到日志时只提示补 --app-log，不会列出一长串研发自查项。\n"
                + "--type 仅支持 memory | thread | auto（兼容别名 oom/heap→memory，deadlock→thread，both→auto）。\n"
                + "活体 heap dump 会先说明 STW/磁盘/服务影响并询问 y/n；脚本/CI 可用 --confirm 等同于回答 y。\n"
                + "thread dump 采集不经过该危险确认。诊断会优先复用目标 JVM 已有 hprof/GC，证据不足才活体采集。\n"
                + "GC/hprof 从不替代 thread dump。推荐 JVM 配置见: jfa help 或 jfa-config（可选证据增强，不是使用前提）。\n";
    }

    public static String diagnoseHelp() {
        return ""
                + "======== jfa-analyze 活体诊断 ========\n"
                + "对正在运行的 Java 进程采集并分析（原 jfa diagnose）。默认全量 = 内存 + 线程；无异常则为健康体检。\n"
                + "控制台只打印 [JFA] 进度与报告路径，不打印报告正文。\n\n"
                + "用法:\n"
                + "  jfa-analyze --pid <pid> [--type auto|memory|thread] [--confirm]\n"
                + "  jfa-analyze --service <name>\n"
                + "  jfa-analyze --pid <pid> --type memory --compare-after 15m [--confirm]\n\n"
                + "参数:\n"
                + "  --pid <pid>              目标 Java 进程 PID\n"
                + "  --service <name>         已登记服务名（不托管生命周期）\n"
                + "  --type <mode>            分析类型：auto（默认，内存+线程）/ memory（内存）/ thread（线程/死锁）\n"
                + "  --confirm                确认危险活体采集（heap dump）；脚本/CI 使用，等同于回答 y\n"
                + "  --compare-after <dur>    活体 A/B：dump1 后等待再 dump2，并由本产品对比（如 15m）\n"
                + "  --app-log <file>         应用日志路径（供日志倒查）\n"
                + "  --hprof <file>           指定 hprof；否则优先复用目标 JVM 已有 dump\n"
                + "  --hprof-prev <file>      上一份 hprof（一般用于离线；活体请用 --compare-after）\n"
                + "  --gc-log <file>          GC 日志文件\n"
                + "  --thread-dump <file>     线程 dump 文件\n"
                + "  --evidence-dir <dir>     证据目录\n"
                + "  --out <dir>              报告输出目录（默认 <install>/reportfile/...）\n"
                + "  --format text|json|both  输出格式。json 时 stdout 为 JSON，路径在 stderr\n"
                + "  --quiet                  关闭中途 [JFA] 进度（仍打印报告路径）\n"
                + "  --verbose                附加更细的路径/体积信息\n"
                + "  --config <path>          配置文件（jfa.properties）\n"
                + "  --help                   显示本帮助\n\n"
                + "说明:\n"
                + "  一次 --confirm 覆盖本命令中的 dump1 与 dump2。thread dump 不走危险确认。\n"
                + "  java -jar 兼容：diagnose --pid <pid> …\n";
    }

    public static String analyzeHelp() {
        return ""
                + "======== jfa-file-analyze 离线分析 ========\n"
                + "对落盘证据分析，不采集活体 dump（原 jfa analyze）。\n"
                + "控制台只打印 [JFA] 进度与报告路径，不打印报告正文。\n\n"
                + "用法:\n"
                + "  jfa-file-analyze --evidence-dir <dir> [--type auto|memory|thread]\n"
                + "  jfa-file-analyze --hprof <file> [--gc-log <file>] [--type memory]\n"
                + "  jfa-file-analyze --hprof <newer> --hprof-prev <older> --type memory\n"
                + "  jfa-file-analyze --thread-dump <file> --type thread\n\n"
                + "参数:\n"
                + "  --evidence-dir <dir>     证据目录（heap/gc/logs/threads 等）\n"
                + "  --hprof <file>           堆 dump（较新的一份）\n"
                + "  --hprof-prev <file>      上一份堆 dump，供本产品对比\n"
                + "  --gc-log <file>          GC 日志文件\n"
                + "  --app-log <file>         应用日志（日志倒查）\n"
                + "  --thread-dump <file>     线程 dump 文件\n"
                + "  --type <mode>            分析类型：auto / memory / thread\n"
                + "  --out <dir>              报告输出目录（默认 <install>/reportfile/...）\n"
                + "  --format text|json|both  输出格式。json 时 stdout 为 JSON，路径在 stderr\n"
                + "  --quiet                  关闭中途 [JFA] 进度（仍打印报告路径）\n"
                + "  --verbose                附加更细的路径/体积信息\n"
                + "  --config <path>          配置文件（jfa.properties）\n"
                + "  --help                   显示本帮助\n\n"
                + "说明:\n"
                + "  离线双快照对比用 --hprof 与 --hprof-prev，不会采集。\n"
                + "  java -jar 兼容：analyze --hprof file …\n";
    }

    public static String collectHelp() {
        return ""
                + "======== jfa-collect 采集 ========\n"
                + "对目标进程采集证据，不自动分析（原 jfa collect）。\n\n"
                + "用法:\n"
                + "  jfa-collect threaddump --pid <pid>\n"
                + "  jfa-collect heapdump --pid <pid> [--confirm]\n"
                + "  jfa-collect sample --pid <pid> [--interval 5s] [--duration 60s] [--confirm]\n\n"
                + "子命令:\n"
                + "  threaddump               采集线程 dump（无危险确认）\n"
                + "  heapdump                 采集 heap dump（需确认 / --confirm）\n"
                + "  sample                   jstat 采样（需确认 / --confirm）\n\n"
                + "参数:\n"
                + "  --pid <pid>              目标 Java 进程 PID（必填）\n"
                + "  --confirm                确认危险采集（heapdump / sample）；脚本/CI 等同于回答 y\n"
                + "  --interval <dur>         采样间隔（默认 5s）\n"
                + "  --duration <dur>         采样时长（默认 60s）\n"
                + "  --evidence-dir <dir>     输出目录（默认 <install>/reportfile/...）\n"
                + "  --config <path>          配置文件（jfa.properties）\n"
                + "  --help                   显示本帮助\n\n"
                + "说明:\n"
                + "  heap dump 有 STW / 磁盘 / 服务影响；无 --confirm 且非交互时不会生成 hprof。\n"
                + "  java -jar 兼容：collect heapdump --pid n --confirm\n";
    }
}